Update compile
be more explicit when referencing items in buildpack dir

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,21 +1,30 @@
 #!/usr/bin/env bash
 
-set -e
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+# set -x          # enable debugging
 
-mkdir -p "$1/bin/"
-cp bin/nginx "$1/bin/"
-nginx_version=$(./bin/nginx -V 2>&1 | head -1 | awk '{ print $NF }')
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_file=$3
+
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+
+mkdir -p "$build_dir/bin/"
+cp $bp_dir/bin/nginx "$build_dir/bin/"
+nginx_version=$($bp_dir/bin/nginx -V 2>&1 | head -1 | awk '{ print $NF }')
 echo "-----> nginx-buildpack: Installed ${nginx_version} to app/bin"
-cp bin/start-nginx "$1/bin/"
+cp $bp_dir/bin/start-nginx "$build_dir/bin/"
 echo '-----> nginx-buildpack: Added start-nginx to app/bin'
 
-mkdir -p "$1/config"
+mkdir -p "$build_dir/config"
 
-cp config/mime.types "$1/config/"
+cp $bp_dir/config/mime.types "$build_dir/config/"
 echo '-----> nginx-buildpack: Default mime.types copied to app/config/'
 
-if [[ ! -f $1/config/nginx.conf.erb ]]; then
-	cp config/nginx.conf.erb "$1/config/"
+if [[ ! -f $build_dir/config/nginx.conf.erb ]]; then
+	cp $bp_dir/config/nginx.conf.erb "$build_dir/config/"
 	echo '-----> nginx-buildpack: Default config copied to app/config.'
 else
 	echo '-----> nginx-buildpack: Custom config found in app/config.'
